### Load The Saved Models

#### Import The Required packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch


### Create the Model

In [3]:
model = torch.nn.Sequential(
    # input layer connecting to hidden layer with 8 neurons
    torch.nn.Linear(in_features=4,out_features=8),
    # SET the activation function on the first hidden layer as relu
    torch.nn.ReLU(),
    # Add Another Hidden Layer 4 neurons
    torch.nn.Linear(in_features=8,out_features=4),
    torch.nn.ReLU(),
    # Output layer  
    torch.nn.Linear(in_features=4,out_features=1)
)

In [5]:
list(model.parameters()) # Intial Or the Random Parammeters

[Parameter containing:
 tensor([[-0.4619, -0.3964, -0.2967, -0.0583],
         [ 0.3297,  0.1971,  0.2703,  0.0206],
         [-0.2815, -0.4970, -0.3527, -0.4071],
         [ 0.0470,  0.2595, -0.1958,  0.3531],
         [-0.3918, -0.3719, -0.2211, -0.0427],
         [-0.3394,  0.4907, -0.4582,  0.4767],
         [ 0.0702, -0.0143,  0.4503, -0.1443],
         [ 0.3829, -0.0956,  0.1333,  0.1601]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0472, -0.3173,  0.4180, -0.0230,  0.0065,  0.0297,  0.4724,  0.2666],
        requires_grad=True),
 Parameter containing:
 tensor([[-0.0434,  0.1970,  0.0038,  0.1013, -0.3379,  0.0145, -0.0465,  0.2130],
         [ 0.1720, -0.0827,  0.0980,  0.3009,  0.3280, -0.2167, -0.1469,  0.2700],
         [-0.2287, -0.3289, -0.0472, -0.1697,  0.1575, -0.0454,  0.3411,  0.1216],
         [-0.0173,  0.2208, -0.1514, -0.0014,  0.0968, -0.3105,  0.1859,  0.0273]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.3452, -0.2695,  0.0314, -

### Load The Parameters in the Saved model 

In [6]:
model.load_state_dict(torch.load("Model_for_50_Startups.pth"))

<All keys matched successfully>

In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[-4.5827e-02, -2.6600e-01, -4.2229e-01,  4.4792e-01],
         [-4.8908e-02,  2.8769e-01,  8.6723e-02,  6.7230e+00],
         [-2.0625e-01,  3.0346e-01,  4.8080e-03, -4.5310e+00],
         [ 6.6643e-01,  4.7318e-01, -1.7386e-01,  9.3278e+00],
         [ 4.2682e-01,  1.8181e-01,  2.3347e-01,  5.7988e+00],
         [-3.1558e-01,  5.3668e-01,  1.3341e-01, -9.1475e+00],
         [ 2.1139e-01,  2.3841e-01,  2.5384e-01,  5.1640e+00],
         [ 6.5108e-01,  3.2137e-01,  5.2766e-01,  5.3257e+00]],
        requires_grad=True),
 Parameter containing:
 tensor([ -0.1465,   7.7452,  -5.0962,   9.4098,   6.2356, -10.0284,   7.2384,
           6.8717], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1059,  0.0474, -0.1629,  0.2700,  0.1279, -0.0478, -0.0341, -0.2560],
         [ 0.0115, -0.1329,  0.2750,  0.1091,  0.1799, -0.2505,  0.1364, -0.1751],
         [-0.2138,  0.2616, -0.2384,  0.7446,  0.4939, -0.2879,  0.2231,  0.2397],
         [-0.0469, -0.2407, 