### REgression

In [1]:
import numpy as np
import torch

### Genrate the Data

In [2]:
x = torch.tensor([[1.],[2.],[3.],[4.],[5.],[6.],[7.],[8.],[9.],[10.]])
y = torch.tensor([[3.],[5.],[7.],[9.],[11.],[13.],[15.],[17.],[19.],[21.]])

### Create The Model

In [3]:
model = torch.nn.Linear(in_features=1,out_features=1) # this model has only one neuron that is the perceptron

In [4]:
model

Linear(in_features=1, out_features=1, bias=True)

In [5]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4661]], requires_grad=True),
 Parameter containing:
 tensor([-0.2660], requires_grad=True)]

In [6]:
# define the Hyper parameter
epochs = 100
lr = 0.01
loss_function = torch.nn.MSELoss()
# Optimizer used to optimize the model parameters (weight , bias)
optimizer = torch.optim.SGD(model.parameters(),lr=lr)

### Training loop

In [7]:
for epoch in range(epochs):
    # Forward Propagation
    y_pred = model(x)
    # Loss Calculation
    loss = loss_function(y_pred,y)
    # Zero out the Optimizer before calculating gradients
    optimizer.zero_grad()
    # Calculate the Loss Gradients
    loss.backward()
    optimizer.step()
    

In [8]:
list(model.parameters())

[Parameter containing:
 tensor([[2.0842]], requires_grad=True),
 Parameter containing:
 tensor([0.4135], requires_grad=True)]

In [9]:
# Inference the Model
model(torch.tensor([[11.]]))

tensor([[23.3402]], grad_fn=<AddmmBackward0>)