### Problem Statement : 
- Predict the Value of y using the x variable

In [1]:
import numpy as np
import torch


#### genrate the data

In [2]:
torch.seed = 42

In [3]:
x = torch.tensor([[1.],[2.],[3.],[4.],[5.],[6.],[7.],[8.],[9.],[10.]])
y = torch.tensor([[3.],[5.],[7.],[9.],[11.],[13.],[15.],[17.],[19.],[21.]])

In [4]:
print(x.ndim)

2


In [11]:
### Define Hyperprameter
epochs = 500
lr=0.01


In [12]:
weight = torch.randn(1,requires_grad=True)
bias = torch.randn(1,requires_grad=True)

In [13]:
print(weight)
print(bias)

tensor([1.1318], requires_grad=True)
tensor([-0.1180], requires_grad=True)


In [14]:
print(weight.requires_grad)


True


### Training Loop

In [15]:
for epoch in range(epochs):
    # Forward pass: predict y using linear equation
    y_pred = weight * x + bias

    # Calculate loss
    loss = ((y - y_pred) ** 2).mean()

    # Backward pass: compute gradients
    loss.backward()

    # Update parameters in-place without tracking gradients
    with torch.no_grad():
        weight -= lr * weight.grad
        bias -= lr * bias.grad

        # Reset gradients to zero for the next epoch
    weight.grad.zero_()
    bias.grad.zero_()

In [16]:
print(f"weight : {weight}")
print(f"bias : {bias}")

weight : tensor([2.0170], requires_grad=True)
bias : tensor([0.8813], requires_grad=True)


### Brodcast Opreation
- The opreation perform on the every element of the Array
- x[0]*weightes[0]+weightes...

 ### Inference the Learning

In [18]:
with torch.no_grad():
    y_pred = 11*weight+bias
    print(y_pred)

tensor([23.0688])
