### DataLoader Demo

### Problem Statement
- instead of loading whole dataset , Load it batch by batch

In [1]:
import numpy as np
import pandas as pd
import torch

### Genrate the Dummy Data

In [2]:
#number of rows
number_of_rows = 10000
#number of featuers
number_of_featuers = 20

In [3]:
# genrate the x Data
x = torch.randn(number_of_rows,number_of_featuers)
x

tensor([[-0.5453, -0.7076, -1.7832,  ...,  0.3968, -0.8522, -0.0650],
        [ 1.4904, -1.0033, -0.4297,  ..., -0.6721, -0.7936,  0.2000],
        [-0.2883,  0.4994,  0.9493,  ...,  1.3786, -0.8468, -1.1437],
        ...,
        [-0.2752,  2.3221, -1.3647,  ..., -0.2852, -0.9423, -0.6190],
        [-0.6362, -0.2215,  0.6776,  ...,  1.3593,  1.4047, -1.1140],
        [ 0.4160, -0.0448,  0.4049,  ..., -0.6496,  1.0964,  0.4936]])

In [4]:
x.shape

torch.Size([10000, 20])

In [5]:
# genrate the y data
y = torch.randint(0,2,(number_of_rows,))
y

tensor([0, 0, 0,  ..., 0, 1, 1])

In [6]:
y.shape

torch.Size([10000])

### Create the Tensor Dataset

In [7]:
from torch.utils.data import TensorDataset

# create the dataset  
dataset = TensorDataset(x,y)

In [8]:
dataset.tensors

(tensor([[-0.5453, -0.7076, -1.7832,  ...,  0.3968, -0.8522, -0.0650],
         [ 1.4904, -1.0033, -0.4297,  ..., -0.6721, -0.7936,  0.2000],
         [-0.2883,  0.4994,  0.9493,  ...,  1.3786, -0.8468, -1.1437],
         ...,
         [-0.2752,  2.3221, -1.3647,  ..., -0.2852, -0.9423, -0.6190],
         [-0.6362, -0.2215,  0.6776,  ...,  1.3593,  1.4047, -1.1140],
         [ 0.4160, -0.0448,  0.4049,  ..., -0.6496,  1.0964,  0.4936]]),
 tensor([0, 0, 0,  ..., 0, 1, 1]))

### Create a data Loader

In [9]:
from torch.utils.data import DataLoader
# create the loader to load dataset in Batches
loader = DataLoader(dataset=dataset,batch_size=128,shuffle=True)

In [10]:
# print the loader information
print(f"total number of records : {len(dataset)}")
print(f"batch size of loader : {loader.batch_size} ")
print(f"Total number of Loaders : {len(loader)}")

total number of records : 10000
batch size of loader : 128 
Total number of Loaders : 79


### Iterate over  the dataloader to read the data batch by batch

In [17]:
for (batch_index,(features,labels)) in enumerate(loader):
    print(f"Batch No : {batch_index+1}")
    print(f"data.shape : {features.shape} ")

Batch No : 1
data.shape : torch.Size([128, 20]) 
Batch No : 2
data.shape : torch.Size([128, 20]) 
Batch No : 3
data.shape : torch.Size([128, 20]) 
Batch No : 4
data.shape : torch.Size([128, 20]) 
Batch No : 5
data.shape : torch.Size([128, 20]) 
Batch No : 6
data.shape : torch.Size([128, 20]) 
Batch No : 7
data.shape : torch.Size([128, 20]) 
Batch No : 8
data.shape : torch.Size([128, 20]) 
Batch No : 9
data.shape : torch.Size([128, 20]) 
Batch No : 10
data.shape : torch.Size([128, 20]) 
Batch No : 11
data.shape : torch.Size([128, 20]) 
Batch No : 12
data.shape : torch.Size([128, 20]) 
Batch No : 13
data.shape : torch.Size([128, 20]) 
Batch No : 14
data.shape : torch.Size([128, 20]) 
Batch No : 15
data.shape : torch.Size([128, 20]) 
Batch No : 16
data.shape : torch.Size([128, 20]) 
Batch No : 17
data.shape : torch.Size([128, 20]) 
Batch No : 18
data.shape : torch.Size([128, 20]) 
Batch No : 19
data.shape : torch.Size([128, 20]) 
Batch No : 20
data.shape : torch.Size([128, 20]) 
Batch No 