In [1]:
import torch
import numpy as np

In [7]:
t1 = torch.tensor([10,20,30,40,50,60])
t2 = torch.tensor([1,2,3,4,5,6])

### Add

In [5]:
t1+t2

tensor([11, 22, 33, 44, 55, 66])

In [13]:
t2.add(t1)

tensor([11, 22, 33, 44, 55, 66])

### Sub

In [14]:
t2-t1

tensor([ -9, -18, -27, -36, -45, -54])

In [15]:
t1.sub(t2)

tensor([ 9, 18, 27, 36, 45, 54])

### Mul

In [16]:
t1*t2

tensor([ 10,  40,  90, 160, 250, 360])

### Div

In [18]:
t2/t1

tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000])

### Power

In [20]:
t1.pow(3)

tensor([  1000,   8000,  27000,  64000, 125000, 216000])

### Square root

In [22]:
t1.sqrt()

tensor([3.1623, 4.4721, 5.4772, 6.3246, 7.0711, 7.7460])

### reciprocol sequare root

In [25]:
t1.rsqrt()

tensor([0.3162, 0.2236, 0.1826, 0.1581, 0.1414, 0.1291])

### Exponential

In [23]:
t1.exp()

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13, 2.3539e+17, 5.1847e+21, 1.1420e+26])

### Natural Log

In [26]:
t1.log()

tensor([2.3026, 2.9957, 3.4012, 3.6889, 3.9120, 4.0943])

### Base Log 10

In [27]:
t1.log10()

tensor([1.0000, 1.3010, 1.4771, 1.6021, 1.6990, 1.7782])

### Base Log 2

In [28]:
t1.log2()

tensor([3.3219, 4.3219, 4.9069, 5.3219, 5.6439, 5.9069])

### Absolute Values

In [30]:
t1.abs()

tensor([10, 20, 30, 40, 50, 60])

In [31]:
t1.neg()

tensor([-10, -20, -30, -40, -50, -60])