In [3]:
import torch
import numpy as np

### Matrix Multiplication

In [54]:
t1 = torch.tensor([[10,20,30,40,50,60]])
t2 = torch.tensor([[1,2,3,4,5,6]])
t2=t2.reshape(6,1)
print(t1)
print(f"Shape of t1 : {t1.shape}, t2 : {t2.shape}")

tensor([[10, 20, 30, 40, 50, 60]])
Shape of t1 : torch.Size([1, 6]), t2 : torch.Size([6, 1])


#### Matrix multiplication

In [39]:
t1@t2

tensor([[910]])

In [40]:
t1.matmul(t2)

tensor([[910]])

In [42]:
t1.mm(t2)  ## For 2D

tensor([[910]])

In [50]:
vec = torch.tensor([10,20,30,40,50,60])
res = t1.mv(vec)
print(res)

tensor([9100])


#### Dot Product 

In [94]:
res = torch.dot(t1.squeeze(),t2.squeeze())
res

tensor(910)

#### Inner Product : shapes should same

In [61]:
t2=t2.reshape(1,6)
t1.inner(t2)

tensor([[910]])

#### Outer Product : 

In [67]:
t1=t1.squeeze()
t2=t2.squeeze()
print(torch.outer(t1,t2))

tensor([[ 10,  20,  30,  40,  50,  60],
        [ 20,  40,  60,  80, 100, 120],
        [ 30,  60,  90, 120, 150, 180],
        [ 40,  80, 120, 160, 200, 240],
        [ 50, 100, 150, 200, 250, 300],
        [ 60, 120, 180, 240, 300, 360]])


#### Trace

In [72]:
t3 = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
t3.trace()

tensor(6)

In [75]:
t3.diag()

tensor([1, 2, 3])

#### Matrix inverse

In [87]:
t3 = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0]])

# Calculate inverse
inv_t3 = torch.inverse(t3)

print(inv_t3)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


### Determinant

In [88]:
t3.det()

tensor(-2.)

#### Eigan Values

In [89]:
eigenvalues, eigenvectors = torch.linalg.eig(t3)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 tensor([-0.3723+0.j,  5.3723+0.j])
Eigenvectors:
 tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])
