In [3]:
import torch
import numpy as np

### Histogram Count

In [6]:
x = torch.tensor([1,2,2,3,4,5,6,7,8,9],dtype=float)
hist = torch.histc(x,bins=4,min=1,max=9)
hist

tensor([3., 2., 2., 3.], dtype=torch.float64)

### Count Of Integers

In [9]:
x1 = torch.tensor(x,dtype=int)
x1.bincount()

C:\Users\Hp\AppData\Local\Temp\ipykernel_11440\2146373101.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x1 = torch.tensor(x,dtype=int)


tensor([0, 1, 2, 1, 1, 1, 1, 1, 1, 1])

In [10]:
x = torch.tensor([0,1,1,2])
weights = torch.tensor([1.0,2.0,3.0,4.0])

print(torch.bincount(x, weights=weights))

tensor([1., 5., 4.])


#### torch.coeff()

In [12]:
x=torch.tensor([
    [1.,2.,3.,4.],
    [4.,3.,2.,1.]
])
print(torch.corrcoef(x))

tensor([[ 1., -1.],
        [-1.,  1.]])


#### Covariance matrix

In [15]:
x=  torch.tensor([
    [1.,2.,3.],
    [2.,4.,6.]
])
print(torch.cov(x))

tensor([[1., 2.],
        [2., 4.]])
