### tensor Mmethods

In [1]:
import numpy as np
import torch

### Creation methods

#### Tensor()

In [2]:
tensor = torch.tensor(np.array([10,20,30,40,50,]))
tensor

tensor([10, 20, 30, 40, 50])

In [3]:
# With the sdattype
tensor = torch.tensor(np.array([10,20,30,40,50,]),dtype=torch.float64)
tensor

tensor([10., 20., 30., 40., 50.], dtype=torch.float64)

#### Zeros

In [4]:
tensor =  torch.zeros(5)
tensor

tensor([0., 0., 0., 0., 0.])

In [5]:
tensor =  torch.zeros(5,5,dtype=int)
tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

#### ONES()

In [6]:
# create the tensor with thw value with ones

In [7]:
tensor = torch.ones(3,5,dtype=int)
tensor

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

tensor = torch.eye(5)

In [8]:
tensor = torch.eye(3)
tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:
tensor = torch.arange(0,10,2)
tensor

tensor([0, 2, 4, 6, 8])

In [10]:
tensor=torch.linspace(0,1,5)
tensor

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [11]:
tensor = torch.full((2,2),7)
tensor

tensor([[7, 7],
        [7, 7]])

In [17]:
tensor=torch.rand(3,4)
tensor

tensor([[0.5971, 0.6561, 0.9121, 0.6551],
        [0.9857, 0.5662, 0.7984, 0.4634],
        [0.9729, 0.3916, 0.6642, 0.3209]])

### Shape Manipluation

#### 1.Reshape

In [18]:
tensor = torch.tensor([10,20,30,40,50,60])
tensor

tensor([10, 20, 30, 40, 50, 60])

In [20]:
print(f"Shape of Tensor : {tensor.shape}")
print(f"ndim : {tensor.ndim}")

Shape of Tensor : torch.Size([6])
ndim : 1


In [31]:
tensor_reshaped = tensor.reshape(6,1)
print(f"tensor : {tensor_reshaped}")
print(f"Shape of Tensor : {tensor_reshaped.shape}")
print(f"ndim : {tensor_reshaped.ndim}")

tensor : tensor([[10],
        [20],
        [30],
        [40],
        [50],
        [60]])
Shape of Tensor : torch.Size([6, 1])
ndim : 2


#### Flatten

In [26]:
# Create the 2d tensor
tensor = torch.tensor([[10,20],[30,40],[50,60]])
tensor

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [29]:
tensor_flttened = tensor.flatten()
print(f"tensor : {tensor_flttened}")
print(f"Shape of Tensor : {tensor_flttened.shape}")
print(f"ndim : {tensor_flttened.ndim}")

tensor : tensor([10, 20, 30, 40, 50, 60])
Shape of Tensor : torch.Size([6])
ndim : 1


#### Transpose : t()

In [35]:
print("Befor Transpose : ")
tensor = torch.tensor([[10,20],[30,40],[50,60]])
print(f"tensor : {tensor}")
print(f"Shape of Tensor : {tensor.shape}")
print(f"ndim : {tensor.ndim}")
tensor_transposed = tensor.t()
print("\nAfter Transpose : ")
print(f"tensor : {tensor_transposed}")
print(f"Shape of Tensor : {tensor_transposed.shape}")
print(f"ndim : {tensor_transposed.ndim}")

Befor Transpose : 
tensor : tensor([[10, 20],
        [30, 40],
        [50, 60]])
Shape of Tensor : torch.Size([3, 2])
ndim : 2

After Transpose : 
tensor : tensor([[10, 30, 50],
        [20, 40, 60]])
Shape of Tensor : torch.Size([2, 3])
ndim : 2


#### View

In [54]:
tensor = torch.tensor([10,20,30,40,50,60])
tensor.view(6,1)
tensor.ndim

tensor.reshape(1,1,6)

tensor([[[10, 20, 30, 40, 50, 60]]])

In [61]:
tensor.squeeze(0)

tensor([10, 20, 30, 40, 50, 60])

In [62]:
tensor.unsqueeze(0)

tensor([[10, 20, 30, 40, 50, 60]])